// -----------------------------------------------------------------------------
// GET /dashboard/sw.js
//
// Service worker del dashboard PWA. Servido desde `/dashboard/sw.js` para
// que el scope natural (sin header `Service-Worker-Allowed`) ya sea
// `/dashboard` — basta con registrarlo desde un componente client del
// área dashboard.
//
// Responsabilidades:
//   · Shell offline mínimo (manifest + iconos + página principal cacheada
//     en navegación network-first).
//   · NO interceptar APIs ni rutas de webhook — el dashboard depende de
//     datos frescos en todo momento (caja, agenda en vivo).
//   · NO push notifications todavía — el `sw.js` cliente ya gestiona
//     push para el customer; para staff es V2 (ver TODO al final del
//     archivo).
// -----------------------------------------------------------------------------

export const dynamic = 'force-static'

const SW_SOURCE = `// otracita dashboard service worker — auto-generated by route handler.
const CACHE_NAME = 'otracita-dashboard-v1'

const SHELL = [
  '/dashboard/manifest.webmanifest',
  '/dashboard-icons/icon-192.png',
  '/dashboard-icons/icon-512.png',
  '/dashboard-icons/apple-touch-icon.png',
]

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(SHELL).catch(() => {})),
  )
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      await Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
      await self.clients.claim()
    })(),
  )
})

// Network-first para navegaciones dentro de /dashboard.
// Si la red falla y no hay caché, devolvemos un fallback HTML mínimo.
self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return
  // Solo interceptamos dentro de /dashboard.
  if (!url.pathname.startsWith('/dashboard')) return
  // Nunca tocar APIs ni el propio archivo del SW.
  if (url.pathname.startsWith('/api/')) return
  if (url.pathname === '/dashboard/sw.js') return

  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          // Cachea la última versión del shell de /dashboard para offline.
          const copy = res.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(req, copy)).catch(() => {})
          return res
        })
        .catch(() =>
          caches.match(req).then(
            (cached) =>
              cached ||
              new Response(
                '<!doctype html><meta charset=\"utf-8\"><title>Sin conexión</title>' +
                  '<style>body{font-family:system-ui,-apple-system,sans-serif;background:#F7F3EE;color:#2A1D14;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;padding:24px;text-align:center}h1{font-size:20px;margin:0 0 8px}p{color:#6B5D4F;margin:0;font-size:14px}</style>' +
                  '<h1>Sin conexión</h1><p>Vuelve a intentarlo cuando tengas internet.</p>',
                { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
              ),
          ),
        ),
    )
    return
  }

  // Para assets estáticos del dashboard (iconos del manifest), cache-first.
  if (url.pathname.startsWith('/dashboard-icons/')) {
    event.respondWith(
      caches.match(req).then(
        (cached) =>
          cached ||
          fetch(req).then((res) => {
            const copy = res.clone()
            caches.open(CACHE_NAME).then((cache) => cache.put(req, copy)).catch(() => {})
            return res
          }),
      ),
    )
  }
})

// TODO (V2): push notifications staff-side. Para reusar la infra VAPID
// existente habría que extender la tabla de subscriptions con un campo
// 'scope' (=customer|dashboard) y enrutar los push del dashboard aquí.
`

export function GET() {
  return new Response(SW_SOURCE, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // El SO consulta el SW de vez en cuando para detectar updates;
      // cache cortita.
      'Cache-Control': 'public, max-age=0, must-revalidate',
      'Service-Worker-Allowed': '/dashboard',
    },
  })
}
